# Generated by Django 5.2 on 2025-05-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetion',
            new_name='Question',
        ),
    ]
